### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by jtneal** [shiruken/csullender.com#4]
I just randomly decided to search for "HaloTV Archive" and came across https://csullender.com/halotv and I couldn't believe my eyes. You actually saved the videos and posted the archive online!!!

I had a video on your website 19 years ago (wow). It got seen by the Official Xbox Magazine editor who subsequently did an interview and article about myself, my clan, and the tricks we had discovered and posted in the video. I thought it was lost to time, but thanks to you, I now have a copy of the video. It's not as clear nor as good as I remembered lol but that's 19 years of technology advancements for you. 

Thank you so much for having the foresight to save this stuff and make it available in this modern era.

**Comment by shiruken** [comment]
That's awesome! Glad you were able to find it! If I remember correctly, the videos were typically transcoded so that likely accounts for some of the loss in quality.
